### ISSUE TITLE
Install react-bootstrap package.

### ISSUE THREAD

**Issue by manuel12** [manuel12/django-expense-tracker#6]
This will be needed as it is a dependency in the current template front-end.

All that needs to be added here the is the react-bootstrap package to package.json.

**Comment by JesusC-R** [comment]
Please assign this task to me

**Comment by Anupam2528** [comment]
Hi @manuel12 
I can able to see in package.json that latest react-bootstrap which is 2.8.0 is already added in the package.json.
Could you please let me know if anything else is expected here?

**Comment by manuel12** [comment]
@Anupam2528 @JesusC-R Yes. I've updated the package sometime ago already.

Closing as  finished.
