### ISSUE TITLE
Re-create homepage.html in React.

### ISSUE THREAD

**Issue by manuel12** [manuel12/django-expense-tracker#9]
Create a react page that has the same html structure as `templates/homepage.html`.

**Comment by CodeEvolver** [comment]
well done, @manuel12. I would like to contribute to this project. 
Are there design files to which I can tailor the UI Implementations or would you love me to go about it?

**Comment by manuel12** [comment]
> well done, @manuel12. I would like to contribute to this project. Are there design files to which I can tailor the UI Implementations or would you love me to go about it?

This is finished now but I will have some more tickets in the future :)
